package consultorsismico.Vista;

import consultorsismico.Controlador.Controlador;
import consultorsismico.Modelo.Sismo;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class VentanaSeleccion extends javax.swing.JFrame{

    public VentanaSeleccion(String titulo, Controlador controlador) {
        super(titulo);
        this.controlador = controlador;
        initComponents();
        this.getContentPane().setBackground(new Color(79, 190, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        magnitudMinLbl = new javax.swing.JLabel();
        tituloLbl = new javax.swing.JLabel();
        consultarBtn = new javax.swing.JButton();
        magnitudMaxLbl = new javax.swing.JLabel();
        magnitudMaxLbl1 = new javax.swing.JLabel();
        magnitudMaxLbl2 = new javax.swing.JLabel();
        magnitudMin = new javax.swing.JTextField();
        magnitudMax = new javax.swing.JTextField();
        cualquierMagnitud = new javax.swing.JRadioButton();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        subtitulo1 = new javax.swing.JLabel();
        subtitulo2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        getContentPane().setLayout(new java.awt.GridBagLayout());

        magnitudMinLbl.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        magnitudMinLbl.setText("Magnitud Mínima: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 0, 0);
        getContentPane().add(magnitudMinLbl, gridBagConstraints);

        tituloLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloLbl.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 3, 0, 0);
        getContentPane().add(tituloLbl, gridBagConstraints);

        consultarBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        consultarBtn.setText("Buscar");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 2, 5, 3);
        getContentPane().add(consultarBtn, gridBagConstraints);

        magnitudMaxLbl.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        magnitudMaxLbl.setText("Magnitud Máxima: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        getContentPane().add(magnitudMaxLbl, gridBagConstraints);

        magnitudMaxLbl1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        magnitudMaxLbl1.setText("Fecha inicial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 21, 0, 0);
        getContentPane().add(magnitudMaxLbl1, gridBagConstraints);

        magnitudMaxLbl2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        magnitudMaxLbl2.setText("Fecha final:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 21, 0, 0);
        getContentPane().add(magnitudMaxLbl2, gridBagConstraints);

        magnitudMin.setText("0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 0);
        getContentPane().add(magnitudMin, gridBagConstraints);

        magnitudMax.setText("0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        getContentPane().add(magnitudMax, gridBagConstraints);

        cualquierMagnitud.setBackground(new java.awt.Color(79, 190, 230));
        cualquierMagnitud.setText("Cualquier Magnitud");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 2, 0, 0);
        getContentPane().add(cualquierMagnitud, gridBagConstraints);

        fechaInicial.setMaxSelectableDate(new java.util.Date(1580194872000L));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        getContentPane().add(fechaInicial, gridBagConstraints);

        fechaFinal.setMaxSelectableDate(new java.util.Date(1579503692000L));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        getContentPane().add(fechaFinal, gridBagConstraints);

        subtitulo1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        subtitulo1.setText("MAGNITUD ------------------------------------------------------------------------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 0, 10);
        getContentPane().add(subtitulo1, gridBagConstraints);

        subtitulo2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        subtitulo2.setText("FECHA ------------------------------------------------------------------------------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 10);
        getContentPane().add(subtitulo2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(filler2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        try {
            controlador.buscar(this.Filtro(1), this.Filtro(2));
            JOptionPane.showMessageDialog(this, "Búsqueda se ha realizado correctamente","BUSQUEDA-FINALIZADA",JOptionPane.PLAIN_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Datos incompletos","CONSULTAR-ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSeleccion("Consultar Sismos",new Controlador()).setVisible(true);
            }
        });
    }
    
    public void init(){
        setVisible(true);
    }
    
    public Sismo Filtro(int orden) throws Exception{
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String fecha;
        Double magnitud;
        Sismo sismo = new Sismo();
        switch(orden){
            case 1: {
                fecha = dateFormat.format(fechaInicial.getDate());
                sismo.setFecha(fecha);
                if(cualquierMagnitud.isSelected()){
                    magnitud = 10.10;
                    sismo.setMagnitud(magnitud);
                }
                else{
                    magnitud = Double.parseDouble(magnitudMin.getText());
                    if(!magnitud.isNaN() && magnitud > 0 && magnitud <= 10){
                        sismo.setMagnitud(magnitud);
                    }
                    else{
                        throw new Exception("Datos no corresponden a parámetros aceptados");
                    }
                }
            }break;
            case 2:{
                fecha = dateFormat.format(fechaFinal.getDate());
                sismo.setFecha(fecha);
                if(cualquierMagnitud.isSelected()){
                    magnitud = 10.10;
                    sismo.setMagnitud(magnitud);
                }
                else{
                    magnitud = Double.parseDouble(magnitudMax.getText());
                    if(!magnitud.isNaN() && magnitud > 0 && magnitud <= 10){
                        sismo.setMagnitud(magnitud);
                    }
                    else{
                        throw new Exception("Datos no corresponden a parámetros aceptados");
                    }
                }
            }break;
        }
        return sismo;
    }
    
    private Controlador controlador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarBtn;
    private javax.swing.JRadioButton cualquierMagnitud;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JTextField magnitudMax;
    private javax.swing.JLabel magnitudMaxLbl;
    private javax.swing.JLabel magnitudMaxLbl1;
    private javax.swing.JLabel magnitudMaxLbl2;
    private javax.swing.JTextField magnitudMin;
    private javax.swing.JLabel magnitudMinLbl;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables

}
